# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_xe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets, QtGui, QtPrintSupport
from PyQt5.QtCore import QSize, QSizeF
from PyQt5.QtGui import QTextDocument, QTextCursor, QFont
from PyQt5.QtPrintSupport import QPrinter, QPrintPreviewDialog
from PyQt5.QtWidgets import QPushButton, QInputDialog, QTextEdit, QHBoxLayout

from them_xe import Ui_Dialog
from SqliteHelper import *

font = QFont('Arial', 16)


class VeGuiXeView(QTextEdit):
    dpi = 72
    doc_width = 8 * dpi
    doc_height = 6 * dpi

    def __init__(self):
        super().__init__(readOnly=True)
        self.setFixedSize(QSize(self.doc_width, self.doc_height))

    def build_ve(self, data):
        document = QTextDocument()
        self.setDocument(document)
        document.setPageSize(QSizeF(self.doc_width, self.doc_height))
        document.setDefaultFont(font)
        cursor = QTextCursor(document)
        cursor.insertText(f"Customer Name: {data}\n")


class EditButtonsWidget(QtWidgets.QWidget):
    editCalled = QtCore.pyqtSignal(str)

    def __init__(self, row, col, parent=None, ):
        super(EditButtonsWidget, self).__init__(parent)
        self.row = row
        self.col = col
        self.parent = parent
        btnPrint = QtWidgets.QPushButton('In')
        btnDelete = QtWidgets.QPushButton('Xóa')
        layout = QtWidgets.QHBoxLayout()
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)
        layout.addWidget(btnPrint)
        layout.addWidget(btnDelete)
        self.setLayout(layout)
        btnDelete.clicked.connect(self.deleteBike)
        btnPrint.clicked.connect(self.printDialog)

    @QtCore.pyqtSlot()
    def getAllCellVal(self):
        itmVal = {}
        for col in range(0, 3):
            itm = self.parent.item(self.row, col).text()
            itmVal[col] = str(itm)
        if itmVal:
            self.editCalled.emit(str(itmVal))

    @QtCore.pyqtSlot()
    def deleteBike(self):
        xe_id = self.parent.item(self.row, 0).text()
        helper = SqliteHelper("gui_xe.db")
        helper.edit(f"DELETE FROM xe_gui WHERE id = {xe_id}")
        self.editCalled.emit("Deleted")

    @QtCore.pyqtSlot()
    def printDialog(self):
        so_xe = self.parent.item(self.row, 1).text()
        self.editCalled.emit(so_xe)


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 618)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 181, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.openAddBikeDialog)

        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 81, 1081, 481))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)

        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(390, 10, 181, 51))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setCalendarPopup(True)

        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(210, 10, 181, 51))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.dateEdit_2.setCalendarPopup(True)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 10, 181, 51))
        self.pushButton_2.setObjectName("pushButton_2")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.loaddata()

        layout = QHBoxLayout(self.centralwidget)
        self.veXeView = VeGuiXeView()
        layout.addWidget(self.veXeView)
        # hide the widget right now...
        self.veXeView.setVisible(False)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gửi Xe TNT Gaming"))
        self.pushButton.setText(_translate("MainWindow", "Thêm xe gửi"))
        self.pushButton_2.setText(_translate("MainWindow", "Xuất Excel"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Số xe"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ngày tạo"))
        header = self.tableWidget.horizontalHeader()
        stylesheet = "::section{Background-color:rgb(150,150,1)}"
        header.setStyleSheet(stylesheet)
        header.setMinimumSectionSize(100)
        self.tableWidget.setColumnHidden(0, True)
        self.tableWidget.setColumnWidth(1, 400)
        self.tableWidget.setColumnWidth(2, 150)
        self.tableWidget.setColumnWidth(3, 200)

    def openAddBikeDialog(self):
        text, ok = QInputDialog.getText(self.centralwidget, "Thêm xe", "Nhập số biển số xe")
        if ok and (len(text) != 0):
            self.addBike(str(text))

    def addBike(self, so_xe):
        helper = SqliteHelper("gui_xe.db")
        helper.edit(f"INSERT INTO xe_gui (so_xe) VALUES ('{so_xe}')")
        self.loaddata()

    def actionBtnscallBack(self, values):
        if (values == "Deleted"):
            self.loaddata()
        else:
            self.showPreview(values)

    def showPreview(self, data):
        self.veXeView.build_ve(data)
        self.printpreviewDialog()

    def printpreviewDialog(self):
        previewDialog = QPrintPreviewDialog()
        previewDialog.paintRequested.connect(self.printPreview)
        previewDialog.exec_()

    def printPreview(self, printer):
        self.veXeView.document().print_(printer)

    def loaddata(self):
        helper = SqliteHelper("gui_xe.db")
        bikes = helper.select("SELECT * FROM xe_gui ORDER BY ngay_tao DESC")

        row = 0
        self.tableWidget.setRowCount(len(bikes))
        for bike in bikes:
            self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(str(bike[0])))
            self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(bike[1]))
            self.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(bike[2]))

            buttonWid = EditButtonsWidget(row, 3, self.tableWidget)
            buttonWid.editCalled.connect(self.actionBtnscallBack)
            self.tableWidget.setCellWidget(row, 3, buttonWid)
            row = row + 1


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
